import client from 'prom-client';
import type { Request, Response, NextFunction } from 'express';

/**
 * Prometheus metrics. Scrape `/metrics`. The cardinality rule here: labels are
 * only ever bounded values (route templates, statuses, job kinds) - never ids,
 * queries or logins, which would blow up the series count.
 */
export const registry = new client.Registry();
client.collectDefaultMetrics({ register: registry, prefix: 'devscout_' });

export const httpDuration = new client.Histogram({
  name: 'devscout_http_request_duration_seconds',
  help: 'HTTP request latency by route and status',
  labelNames: ['method', 'route', 'status'] as const,
  buckets: [0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10],
  registers: [registry],
});

export const searchDuration = new client.Histogram({
  name: 'devscout_search_duration_seconds',
  help: 'Hybrid search latency by ranking mode',
  labelNames: ['mode'] as const,
  buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2],
  registers: [registry],
});

export const githubCalls = new client.Counter({
  name: 'devscout_github_api_calls_total',
  help: 'Calls made to the GitHub REST API by endpoint group and outcome',
  labelNames: ['endpoint', 'outcome'] as const,
  registers: [registry],
});

export const githubRateRemaining = new client.Gauge({
  name: 'devscout_github_rate_limit_remaining',
  help: 'Remaining GitHub API quota as last reported by a response header',
  registers: [registry],
});

export const jobsProcessed = new client.Counter({
  name: 'devscout_ingest_jobs_total',
  help: 'Ingestion jobs finished, by kind and terminal status',
  labelNames: ['kind', 'status'] as const,
  registers: [registry],
});

export const jobDuration = new client.Histogram({
  name: 'devscout_ingest_job_duration_seconds',
  help: 'Ingestion job wall time by kind',
  labelNames: ['kind'] as const,
  buckets: [0.1, 0.5, 1, 2.5, 5, 10, 30, 60],
  registers: [registry],
});

export const queueDepth = new client.Gauge({
  name: 'devscout_queue_depth',
  help: 'Jobs waiting in the ingestion queue',
  labelNames: ['queue'] as const,
  registers: [registry],
});

export const cacheEvents = new client.Counter({
  name: 'devscout_cache_events_total',
  help: 'Cache hits and misses by namespace',
  labelNames: ['namespace', 'result'] as const,
  registers: [registry],
});

export const embeddingCalls = new client.Counter({
  name: 'devscout_embedding_calls_total',
  help: 'Embeddings generated by provider and outcome',
  labelNames: ['provider', 'outcome'] as const,
  registers: [registry],
});

export const dbQueryDuration = new client.Histogram({
  name: 'devscout_db_query_duration_seconds',
  help: 'Postgres query latency by logical operation',
  labelNames: ['op'] as const,
  buckets: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5],
  registers: [registry],
});

/**
 * Times every request. `req.route` only exists after routing, so the label is
 * read in the finish handler and falls back to a literal for unmatched paths.
 */
export function httpMetrics(req: Request, res: Response, next: NextFunction) {
  const end = httpDuration.startTimer({ method: req.method });
  res.on('finish', () => {
    const route = (req.route?.path && `${req.baseUrl}${req.route.path}`) || req.baseUrl || 'unmatched';
    end({ route, status: String(res.statusCode) });
  });
  next();
}
